#!/usr/bin/env python3

import re

#def is_symbol( t ):
#    return re.match( "[a-z_A-Z][0-9a-z_A-Z]*", t ) is not None

kw_if = ( "if", "keyword" )
kw_for = ( "for", "keyword" )
kw_in = ( "in", "keyword" )

def format( tokens ):
    ret = ""
    first = True
    indent = 0
    for tok in tokens:
        if len(tok[0]) > 1:
            t = tok[0]
        else:
            t = tok
        if t == "}":
            indent -= 1
            ret += "    " * indent + t + "\n"
            first = True
        elif t == "{":
            ret += "\n" + "    " * indent + t + "\n"
            first = True
            indent += 1
        elif first:
            first = False
            ret += "    " * indent + t
        elif t == "(" and not after_kw:
            ret += t
        elif t == ",":
            ret += t
        elif t == ";":
            ret += t + "\n"
            first = True
        else:
            ret += " " + t

        try:
            after_kw = ( tok[1] == "keyword" )
        except IndexError:
            after_kw = False

    return ret


def assert_equal( act, exp ):
    act = act.strip()
    exp = exp.strip()
    if act != exp:
        raise AssertionError( "\n" + act + "\n!=\n" + exp )

assert_equal(
    format(["int", "x", "=", "0", ";"]),
    """
int x = 0;
"""
)


assert_equal(
    format(["int", "x", "=", "0", ";", "x", "+=", "1", ";"]),
    """
int x = 0;
x += 1;
"""
)


assert_equal(
    format([kw_if, "(", "x", "==", "0", ")", "{", "x", "=", "1", ";", "}"]),
    """
if ( x == 0 )
{
    x = 1;
}
"""
)


assert_equal(
    format(
        [
            kw_if, "(", "x", "==", "0", ")",
            "{",
                "x", "=", "1", ";",
            "}",
            "x", "+=", "1", ";"
        ]
    ),
    """
if ( x == 0 )
{
    x = 1;
}
x += 1;
"""
)


assert_equal(
    format(
        [
            kw_if, "(", "x", "==", "0", ")",
            "{",
                kw_for, "(", "y", kw_in, "zs", ")",
                "{",
                    "x", "=", "1", ";",
                "}",
            "}",
        ]
    ),
    """
if ( x == 0 )
{
    for ( y in zs )
    {
        x = 1;
    }
}
"""
)


assert_equal(
    format(
        [
            "abc", "(", "11111111", ",", "22222222", ")", ";"
        ]
    ),
    """
abc( 11111111, 22222222 );
"""
)

assert_equal(
    format(
        [
            "a" * 75, "(", "11111111", ",", "22222222", ")", ";"
        ]
    ),
    """
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(
    11111111, 22222222 );
"""
)

